spring.application.name=demo
# DataBase h2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

#jwt config
spring.app.jwt.secret=MqozzryTbL8o4uvu63dEQrskZfDUNJJAtXlwDJkD3U5
spring.app.jwt.expiration=86400


# Swagger Path
springdoc.swagger-ui.path=/api/docs


# Si en su readme les piden usar variables de entorno hay que pasar todo estos valores a un archivo .env 
# Ejemplo:
# 
#  Antes del env :
# 
#   spring.app.jwt.secret=MqozzryTbL8o4uvu63dEQrskZfDUNJJAtXlwDJkD3U5
#   spring.app.jwt.expiration=86400
#
#  Despues del env :  
#  
#   spring.app.jwt.secret=${JWT_SECRET}
#   spring.app.jwt.expiration=${JWT_EXPIRATION}
#

